### ISSUE TITLE
 [wrong number of arguments (3 for 2)]

### ISSUE THREAD

**Issue by wtanaka** [ahelal/kitchen-ansiblepush#35] opened 2016-12-31 02:39 UTC
@ahelal 

With: Installing kitchen-ansiblepush 0.5.1

https://travis-ci.org/wtanaka/ansible-role-docker/jobs/187749086
https://travis-ci.org/wtanaka/role-tester-ansible/jobs/187840614

With: Installing kitchen-ansiblepush 0.5.2

<s>https://travis-ci.org/wtanaka/ansible-role-docker/jobs/187833339</s> (I'm rebuilding this with 0.5.1 pinned)
https://travis-ci.org/wtanaka/role-tester-ansible/builds/187848434 (building, and will presumably fail)

**Comment by ahelal** [comment] 2016-12-31 10:50
@wtanaka thank you for reporting this, I am unable to reproduce it. Is it possible to to run it with ```-l debug``` to get the stacktrace ?

**Comment by wtanaka** [comment] 2016-12-31 11:38
@ahelal 
https://semaphoreci.com/wtanaka/role-tester-ansible/branches/dev/builds/2

**Comment by ahelal** [comment] 2016-12-31 12:49
@wtanaka
I have a fix, Can you add this to your gemfile ```gem 'kitchen-ansiblepush', :git => 'https://github.com/ahelal/kitchen-ansiblepush.git', :branch => 'Fix/chef'```

And give it a try if it works will merge and a do another release.

**Comment by wtanaka** [comment] 2016-12-31 14:39
@ahelal fix/chef branch is looking good

**Comment by ahelal** [comment] 2016-12-31 14:53
Fixed with #36  and release 0.5.3

**Closed as completed by ahelal** 2016-12-31 14:53 UTC
